### ISSUE TITLE
permission denied

### ISSUE THREAD

**Issue by konk22** [DrumClock/mount_copy#1]
Hello! Help me fix the problem. When connecting usb in the error log:

mount: /tmp/tmp.bhc4hWmKew: permission denied.
mount: /tmp/tmp.uu7OW9g3Mq: permission denied.

**Comment by DrumClock** [comment]
Hi, unfortunately I don't get these errors.
So I can't say where the problem is.
Try uninstalling/rebooting and reinstalling

**Comment by konk22** [comment]
Good job! I modified your code, published it and left a link to your repository. Thanks!
https://github.com/konk22/3Def_Voron_2.4r2/tree/main/manual/klipper_usb_autocopy

**Comment by DrumClock** [comment]
Hi, may I know what adjustments you made?
A friend programmed it, I just provided it.
